# Generated by Django 4.2.5 on 2023-10-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('discount', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('imageUrl', models.URLField()),
                ('category', models.CharField(choices=[('supermarket', 'Supermercado'), ('tecnology', 'Tecnologia'), ('house-and-furniture', 'Casa e Móveis'), ('home-appliances', 'Eletrodomésticos'), ('sports-and-fitness', 'Esportes e Fitness'), ('tools-and-construction', 'Ferramentas e Construção'), ('health', 'Saúde'), ('beauty-and-self-care', 'Beleza e Cuidado Pessoal'), ('fashion', 'Moda'), ('babies', 'Bebês'), ('toys', 'Brinquedos'), ('aerospace', 'Aeroespacial'), ('military', 'Bélicos')], max_length=22)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
