# Generated by Django 4.2.5 on 2023-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bodega_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
