# Generated by Django 4.2.5 on 2023-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bodega_web', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
