# Generated by Django 4.2.5 on 2023-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bodega_web', '0003_alter_product_discount_alter_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.FloatField(),
        ),
    ]
