# Generated by Django 4.2.5 on 2023-10-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bodega_web', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='stock',
            new_name='amount',
        ),
    ]
